services:
  payment-gateway:
    build:
      context: .
      target: development
    container_name: payment-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WEBHOOK_SECRET=local-webhook-secret-key
      - API_KEY=local-api-key-123
      - QUEUE_CONCURRENCY=2
      - LOG_LEVEL=debug
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - payment_gateway_node_modules:/app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - payment-network

networks:
  payment-network:
    name: payment-network

volumes:
  payment_gateway_node_modules: